### ISSUE TITLE
Incorrect preg_replace expr in field.chunks.php

### ISSUE THREAD

**Issue by venomjke** [pyrocms/pyrocms#3454]
After update from 2.0.x to 2.5 i found a bug.

preg expr :
```
/[^a-zA-Z0-9_-\s]/
```

generate error `preg_match(): Compilation failed: invalid range in character class at offset ...`

escaping `-` solved the problem

correct expr:
```
/[^a-zA-Z0-9_\-\s]/
```

**Comment by huglester** [comment]
Hello

`After update from 2.0.x to 2.5 i found a bug.`
maybe you mean upgrading PHP version?

What version are you on?

**Comment by RyanThompson** [comment]
PR it up - sounds legit though - old chunks coming into the new (deprecated) chunks.

**Comment by huglester** [comment]
wasn't this an actual fix? 
https://github.com/pyrocms/pyrocms/commit/fa8250fc42f46d6d66b1b433914622e99eb97f67
